name: Spanish word ci
on:
  push:
    branches: [ main ]
env:
    E2E_BASE_URL: 'https://spanish-cards.netlify.app/'
jobs:
  Build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Build the app
      run: npm run build
  UnitTest:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run unit test
      run: npm run test:unit
  IntegrationTest:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: npm ci
      run: npm ci
    - name: install browser and its dependencies
      run: npx playwright install --with-deps
    - name: npx playwright test
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      with:
        name: Report e2e test
        path: reports-e2e/html
  MockDeployment:
    runs-on: ubuntu-latest
    needs: IntegrationTest
    steps:
    - name: Mock Deployment
      run: echo "Mocking deployment"
  E2ETest:
    runs-on: ubuntu-latest
    needs: MockDeployment
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: npm ci
      run: npm ci
    - name: Echo website host
      run: echo "$E2E_BASE_URL"
    - name: run e2e test
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      with:
        name: Report e2e
        path: reports-e2e/html
